name: Sec Pipeline

on: 
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  Aikido:
    uses: ./.github/workflows/aikido.yml
    secrets: inherit
